# Generated by Django 5.2.8 on 2026-02-17 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='graphs',
            name='graph_structure',
        ),
        migrations.CreateModel(
            name='nodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.CharField(max_length=255)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.graphs')),
            ],
        ),
        migrations.CreateModel(
            name='edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_node', to='back.nodes')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_node', to='back.nodes')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.relationship')),
            ],
            options={
                'unique_together': {('from_node', 'to_node', 'relation')},
            },
        ),
    ]
