# Generated by Django 5.2.8 on 2026-02-21 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_relationship_remove_graphs_graph_structure_nodes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphs',
            name='name',
            field=models.CharField(default='ando manejando', max_length=100),
            preserve_default=False,
        ),
    ]
